spring:
  application:
    name: weshopify-customers-mgmt-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  profiles:
    active:
    - qa    
server:
  port: 5051
  

  

--- 
#Dev Profile
spring: 
 datasource: 
  url: jdbc:mysql://${CUSTOMERS_DB_HOST:localhost}:${CUSTOMERS_DB_PORT:3306}/${CUSTOMERS_DB:weshopify-customers-db}
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${CUSTOMERS_DB_USER_NAME:root}
  password: ${CUSTOMERS_DB_USER_PASSWORD:root}
 
 config:
    activate:
      on-profile:
      - dev
---
#QA Profile
spring: 
 datasource: 
  url: jdbc:h2:mem:${CUSTOMERS_DB:weshopify-customers-db}
  driver-class-name: org.h2.Driver
  username: ${CUSTOMERS_DB_USER_NAME:sa}
  password: ${CUSTOMERS_DB_USER_PASSWORD:admin}
 h2:
    console:
      enabled: true
      path: /h2Console
 
 config:
    activate:
      on-profile:
      - qa
