spring:
  application:
    name: weshopify-categories-mgmt-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  profiles:
    active:
    - qa    
server:
  port: 5052
  

  

--- 
#Dev Profile
spring: 
 datasource: 
  url: jdbc:mysql://${CATEGORIES_DB_HOST:localhost}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB:weshopify-categories}
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${CATEGORIES_DB_USER_NAME:root}
  password: ${CATEGORIES_DB_USER_PASSWORD:root}
 
 config:
    activate:
      on-profile:
      - dev
---
#QA Profile
spring: 
 datasource: 
  url: jdbc:h2:mem:${CATEGORIES_DB:weshopify-categories}
  driver-class-name: org.h2.Driver
  username: ${CATEGORIES_DB_USER_NAME:sa}
  password: ${CATEGORIES_DB_USER_PASSWORD:admin}
 h2:
    console:
      enabled: true
      path: /h2Console
 
 config:
    activate:
      on-profile:
      - qa
