spring:
  application:
    name: weshopify-categories-mgmt-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  profiles:
    active:
    - dev  
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  
server:
  port: 5052
  
eureka:
  client:
    service-url: 
      defaultzone: http://localhost:8761/
    fetch-registry: true
    register-with-eureka: true
  

--- 
#Dev Profile
spring: 
 datasource: 
  url: jdbc:mysql://${CATEGORIES_DB_HOST:localhost}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB:weshopify-categories}
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${CATEGORIES_DB_USER_NAME:root}
  password: ${CATEGORIES_DB_USER_PASSWORD:root}
 
 config:
    activate:
      on-profile:
      - dev
---
#QA Profile
spring: 
 datasource: 
  url: jdbc:h2:mem:${CATEGORIES_DB:weshopify-categories}
  driver-class-name: org.h2.Driver
  username: ${CATEGORIES_DB_USER_NAME:sa}
  password: ${CATEGORIES_DB_USER_PASSWORD:admin}
 h2:
    console:
      enabled: true
      path: /h2Console
 
 config:
    activate:
      on-profile:
      - qa
